trigger:
  branches:
    include:
      - main

pool:
  name: BNDZ  # Use your private agent pool

variables:
  kubernetesServiceConnection: 'aks-connection'  # Replace with your actual service connection name
  namespace: 'default'  # Change if using a custom namespace

stages:
- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: DeployJob
    displayName: Deploy Kubernetes Manifests
    steps:

    - checkout: self

    - task: Kubernetes@1
      displayName: Deploy MongoDB
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(namespace)
        command: apply
        useConfigurationFile: true
        configuration: Manifest/mongodb.yaml

    - task: Kubernetes@1
      displayName: Deploy Backend
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(namespace)
        command: apply
        useConfigurationFile: true
        configuration: Manifest/backend.yaml

    - task: Kubernetes@1
      displayName: Deploy Frontend
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(namespace)
        command: apply
        useConfigurationFile: true
        configuration: Manifest/frontend.yaml

    - task: Kubernetes@1
      displayName: Deploy Ingress
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(namespace)
        command: apply
        useConfigurationFile: true
        configuration: Manifest/ingress.yaml
